### PR TITLE
Use Authenticate URL instead of Authorize URL and Update to Spring Security Core 2.0

### PR DESCRIPTION
**Pull request by Eylen**
I think it would be better if Twitter AuthenticateURL is used instead of Authorize URL to allow skipping the application approval page if you've already approved it before.
Also I've uploaded an update to Spring Security Core 2.0

### CODE REVIEW

**Comment by thody** [comment]
+1 for authenticate URL, nearly made this pull request myself.

**Comment by splix** [comment]
Hi, thank you Eylen. 
Sorry for delay, going to merge your pull request. Just wasn't sure about migrating to Spring Security Core 2

**Comment by splix** [comment]
Released in v0.6

**Comment by thody** [comment]
Thanks!

**Pull request merged**
